services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-app
    ports:
      - "127.0.0.1:5005:5000"
    environment:
      - TELNYX_API_KEY=${TELNYX_API_KEY}
      - LLM_API_URL=${LLM_API_URL}
      - USE_OPENAI=${USE_OPENAI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EMBEDDING_API_URL=${EMBEDDING_API_URL}
      - TELNYX_FROM=${TELNYX_FROM}
      - TELNYX_PROFILE_ID=${TELNYX_PROFILE_ID}
    volumes:
      - ./chroma_data:/app/chroma_data
volumes:
  chroma_data:
